### ISSUE TITLE
Flakey ING Unit Test

### ISSUE THREAD

**Issue by cding21** [cding21/Expense-Tracker-v2#42]
**Describe the bug**
Unit test fails during build phase on deployment (passes on GitHub actions but always fails on deployment, might be due to network restrictions of the container)

**Expected behavior**
This unit test should pass without timeouts

**Comment by thebowenfeng** [comment]
Isn't test and build ran on the same job?

**Comment by cding21** [comment]
Atm the build stage on GitHub actions isn't doing anything, the built image doesn't get uploaded to a repository anywhere (I probably should make it work like this). The ACTUAL build phase in done on DigitalOcean through their build pipeline.

**Comment by thebowenfeng** [comment]
Oh ok why not just remove build from Github? Also since there's two pipelines what happens when a test fails on Github would that stop the deploy on digitalocean?

**Comment by cding21** [comment]
I wanna eventually move to publishing the docker image from GitHub actions rather than relying on the DigitalOcean build process. Stops the case where tests fail here and deployment still goes ahead

**Comment by thebowenfeng** [comment]
Is this still an issue

**Comment by cding21** [comment]
I silenced the test in a try catch lol, i lowkey want to just get rid of that test

**Comment by cding21** [comment]
Have opted to delete this test for now, way too big of a head-ache for deployment w/ docker
